Add Readme, e_methods.rb and linters files
carloso0114/ruby_enumerators pull request #1
Opened 2020-12-03 17:13 UTC by carloso0114

This project consisted of re-building some of the most used enumerable methods in Ruby: each, my_each_with_inde, my_select, my_all?, my_any?, my_none?, my_count, my_map, my_inject, and an extra method called 'multiply_els'.
For this project we used Ruby, Git, and Rubocop.
For documentation and learning we used the ruby-docs site, stackoverflow, and codecademy.

2020-12-04 21:34 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below:
 
 
## [REQUIRED CHANGES]
- [x] Note that your methods should work exactly as the built-in ruby methods, you can find all of them here: https://ruby-doc.org/core-2.7.1/
- [x] I've made some comments down below, please check what was expected and what was actually given, with that info you guys can search what was the issue and how to solve it;

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-12-04 21:34 UTC, kevincappuccino commented on e_methods.rb
> +    if block_given? && !argum.nil?
#my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
     Failure/Error: expect(array.my_all?(3)).to be array.all?(3)

       expected false
            got true

2020-12-04 21:34 UTC, kevincappuccino commented on e_methods.rb
> +    if block_given? && !argum.nil?
when no block or argument is given returns false if at least one of
the collection is not true
     Failure/Error: expect(false_array.my_any?).to be false_array.any?

       expected false
            got true

2020-12-04 21:34 UTC, kevincappuccino commented on e_methods.rb
> +    if block_given? && !argum.nil?
1- returns false if the block ever returns true for all elements::range
     Failure/Error: expect(range.my_none?(&false_block)).to eq(range.none?(&false_block))
 ```
      expected: false
            got: true
```
      note: It was compared using ==;

2- when no block or argument is given returns false only if one of the collection members is true
     Failure/Error: expect(true_array.my_none?).to be false

       expected false
            got true

3- when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
     Failure/Error: expect(words.my_none?(5)).to be words.none?(5)

       expected false
            got true

2020-12-04 21:34 UTC, kevincappuccino commented on e_methods.rb
> +    if !block_given?
Should raise a "LocalJumpError" when no block or argument is given
     Failure/Error: expect { array.my_inject }.to raise_error(LocalJumpError)
       expected LocalJumpError but nothing was raised

2020-12-05 02:03 UTC, elmejdki requested changes
# status: require changes :recycle: 

Impressive work @team, you are almost there, you have actually left some of the required changes by the previous TSE don't worry I will give you more details so you know how to solve them.

## Required changes:

Please check the comments below :point_down: :point_down: :point_down: :point_down: :point_down: 

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_Feel free to contact me on slack if you have any questions._

2020-12-05 02:03 UTC, elmejdki commented on e_methods.rb
> +  end
## my_all?:

- [x] when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern:

```ruby

    array = [23, 43, 56, 2, 64, 76, 30, 16, 43, 26]
    array.my_all?(3) === array.all?(3) => false

```

2020-12-05 02:03 UTC, elmejdki commented on e_methods.rb
> +  end
## my_any?:

- [ ]  returns false if the block never returns true for all elements::range:

```ruby

      range = Range.new(5, 50)
      false_block = proc { |num| num > 51 }
      range.my_none?(&false_block) === range.none?(&false_block) => false

```

2020-12-05 02:03 UTC, elmejdki commented on e_methods.rb
> +  end
and this [review](https://github.com/carloso0114/ruby_enumerators/pull/1/files#r536390674) you have forgotten to work on, it's super clear I think.

`
Should raise a "LocalJumpError" when no block or argument is given
Failure/Error: expect { array.my_inject }.to raise_error(LocalJumpError)
expected LocalJumpError but nothing was raised
`

2020-12-05 21:34 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job guys :100: :1st_place_medal: , thanks for making the required changes:+1:.

now you can merge to development you project is approved.

## Happy Coding :tophat:

2020-12-05 21:40 UTC, merged